version: "3"

networks:
  shared_network:
    external:
      name: shared_network

services:
  docker-tick:
    build: .
    volumes:
      - ./etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./data/influxdb:/var/lib/influxdb
      - ./data/chronograf:/var/lib/chronograf
      - ./data/kapacitor:/var/lib/kapacitor
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8088:8088"
      - "8888:8888"
    entrypoint:
      - "/usr/local/bin/start.sh"
    deploy:
      mode: replicated
      replicas: 2
      resources:
      # Hard limit - Docker does not allow to allocate more
        limits:
          cpus: '0.25'
          memory: 512M
      # Soft limit - Docker makes best effort to return to it
        reservations:
          cpus: '0.25'
          memory: 256M
